# Generated by Django 3.2.13 on 2022-04-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_city_name', models.CharField(max_length=50)),
                ('airport_abreviation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=50)),
                ('carrier_rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_name', models.CharField(max_length=50)),
                ('plane_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_datetime', models.DateTimeField()),
                ('flight_price', models.IntegerField()),
                ('flight_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('flight_source_city', models.CharField(max_length=50)),
                ('flight_destination_city', models.CharField(max_length=50)),
                ('flight_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis1.carrier')),
                ('flight_destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destination_airport', to='apis1.airport')),
                ('flight_plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis1.plane')),
                ('flight_source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_source_airport', to='apis1.airport')),
            ],
        ),
    ]
