# Generated by Django 3.2.13 on 2022-04-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_carrier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_destination_airport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_plane',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_source_airport',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='flight2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_datetime', models.DateTimeField()),
                ('flight_price', models.IntegerField()),
                ('flight_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('flight_source_city', models.CharField(max_length=50)),
                ('flight_destination_city', models.CharField(max_length=50)),
                ('flight_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis1.carrier')),
                ('flight_destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destination_airport', to='apis1.airport')),
                ('flight_plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis1.plane')),
                ('flight_source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_source_airport', to='apis1.airport')),
            ],
        ),
    ]
